### ISSUE TITLE
Cards. Research business registration in Singapore with Sleek

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/card-issuance#2]
### Notice
This was originally authored by @sergfeldman 

### Background
This is one of the streams in the Ubiquity cards issuing.
[Airwallex](https://www.airwallex.com/) preliminary confirmed that the Ubiquity case is ok for card issuing.
Airwallex recommended [Sleek](https://sleek.com/) as a business registration partner in Singapore.

The goal of the stream is to issue cards by Airwallex from a non-crypto business entity registered in Singapore via Sleek.

### Actionable steps
- [x] ubiquity/card-issuance#3
- [x] ubiquity/card-issuance#4
- [x] ubiquity/card-issuance#5
- [x] Compile Sleek recommendations on registration, licensing, etc.
- [ ] Clarify licensing aspects in Singapore for the Ubiquity case (can be a sub-task).
- [ ] Clarify tax policy and tax exemption in Singapore for the Ubiquity case which is a startup marketplace (can be a sub-task).
- [ ] Compile the exact requirements for the documentation necessary for the business registration with Sleek.
- [ ] Discuss in Ubiquity the business registration in Singapore, describes the requirements to Ubiquity, and get the Ubiquity inputs and questions.
- [ ] Collect all documentation necessary for the business registration with Sleek.
- [ ] Check the collected documentation with Sleek and update if needed, get the final price and time estimate from Sleek.
- [ ] Re-check with Airwallex and Sleek that this business registration will allow Ubiquity to issue cards.
- [ ] Make in Ubiquity the final decision on the business registration in Singapore with Sleek.

### Acceptance criteria

**Main**
- The ability of business registration in Singapore with Sleek is researched and a proper decision is made by Ubiquity.

**Additional**
- Licensing aspects in Singapore for the Ubiquity case are clarified.
- Tax policy in Singapore for the Ubiquity case is clarified.

### Time estimate
Preliminary, several weeks.
The timeline depends on the interim results and decisions, as well as external partners.
